#!/bin/sh

# Create a test project to ensure it does not fail.

set -euo pipefail

test_project_name="new_project"

rm -rf ${test_project_name} || true

uv sync

echo "==> Creating and testing temporary test project '${test_project_name}'…"
uvx cookiecutter . --no-input

cd ${test_project_name}
make setup
make format
make lint
make test
make run
make docker-build
make docker-run

echo "==> Removing '${test_project_name}'..."
rm -rf ${test_project_name}}

echo "==> Successfully created and tested a new project"
