#!/bin/sh

# Define global variables and functions to source in other scripts.

set -euo pipefail

PROJECT_NAME="{{cookiecutter.project_slug}}"
ROOT_DIR="$(dirname "$0")/.."
SRC_DIR="${ROOT_DIR}/${PROJECT_NAME}"
TESTS_DIR="${ROOT_DIR}/tests"

DOCKER_IMAGE_TAG="${PROJECT_NAME}:local"

function activate_venv() {
    source "${ROOT_DIR}/venv/bin/activate"
}

function echo_step() {
    echo "==> $1..."
}

# ensure stdout and stderr are not buffered
export PYTHONUNBUFFERED="1" 
export PYTHONPATH="${ROOT_DIR}"
