#!/bin/sh

# Build a docker image for the app.

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/_global
activate_venv

echo_step "Building docker image '${DOCKER_IMAGE_TAG}'"
docker build -t "$DOCKER_IMAGE_TAG" -f Dockerfile .
