#!/bin/sh

# Lint source code.

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/_global
activate_venv

echo_step "Checking ruff formatting"
ruff format --check ${SRC_DIR} ${TESTS_DIR}

echo_step "Checking isort formatting"
isort --check ${SRC_DIR} ${TESTS_DIR}

echo_step "Linting with ruff"
ruff check ${SRC_DIR}

echo_step "Linting with mypy"
mypy ${SRC_DIR}
