#!/bin/sh

# Lint source code.

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/_global
activate_venv

echo_step "Checking black formatting"
black --check ${SRC_DIR} ${TESTS_DIR}

echo_step "Checking isort formatting"
isort --check ${SRC_DIR} ${TESTS_DIR}

echo_step "Running ruff"
ruff check ${SRC_DIR}

echo_step "Running mypy"
ruff check ${SRC_DIR}
