#!/bin/sh

# Publish the package to pypi.org.

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/_global

python3 -m venv /tmp/venv
soure /tmp/venv/bin/activate

echo_step "Building the package"
pip install --upgrade build twine
python -m build

echo_step "Uploading the package to pypi.org"
python -m twine upload --repository pypi dist/*

rm -rf dist
rm -rf /tmp/venv
