name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.11
    
    - name: Install just
      run: sudo snap install --edge --classic just

    - name: Install module in venv
      run: just setup

    - name: Run tests
      run: just test

    - name: Run linters
      run: just lint
