name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.12
    
    - name: Setup the local environment
      run: make setup

    - name: Run linters
      run: make lint

    - name: Run tests
      run: make test
